pipeline {
    agent any

    environment {
        POSTMAN_API_KEY = credentials("postman-api-key")
    }

    stages {

        stage('Postman CLI Login') {
            steps {
                sh 'postman login --with-api-key $POSTMAN_API_KEY'
            }
        }

        stage('Running collection') {
            steps {
                sh '''
                mkdir -p postman

                postman collection run 47269879-18fadf9f-8a64-41f4-a986-4b9800c9f24c \
                --reporters cli,html,junit \
                --reporter-html-export postman/report.html \
                --reporter-junit-export postman/junit-report.xml
                '''
            }
        }

        stage('Publish JUnit Report') {
            steps {
                junit 'postman/junit-report.xml'
            }
        }
    }
}
